In [ ]:
import pandas as pd
import pdfkit as pk

In [ ]:
numeros = [10, 20, 30, 40]
nomes = ["Bianca", "Adrinne", "Marcus", "Patrick", "Guilherme"]

turma = {
    "Nome": ["Bianca", "Adrinne", "Marcus", "Patrick", "Guilherme", "Denis", "Enzo"],
    "Idade": [22, 29, 15, 45, 21, 40, 20],
    "Genero": ["F", "F", "M", "M", "I", "T", "M"]
}

serie.numeros = pd.Series(numeros)
serie.nomes = pd.Series(nomes)
df = pd.DataFrame(turma)

In [ ]:
print (serie)
print (serie.nomes)

In [ ]:
html = df.to_html("turmas.html", index=False
pk.from_string(html, "tabela.pdf")

In [22]:
print(df)

        Nome  Idade Genero
0     Bianca     22      F
1    Adrinne     29      F
2     Marcus     15      M
3    Patrick     45      M
4  Guilherme     21      I
5      Denis     40      T
6       Enzo     20      M

In [25]:
df.head(20)

        Nome  Idade Genero
0     Bianca     22      F
1    Adrinne     29      F
2     Marcus     15      M
3    Patrick     45      M
4  Guilherme     21      I
5      Denis     40      T
6       Enzo     20      M

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    7 non-null      object
 1   Idade   7 non-null      int64
 2   Genero  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [27]:
df.describe()

           Idade
count   7.000000
mean   27.428571
std    11.178210
min    15.000000
25%    20.500000
50%    22.000000
75%    34.500000
max    45.000000

In [30]:
df.columns

Index(['Nome', 'Idade', 'Genero'], dtype='object')

In [31]:
df["Nome"]

0       Bianca
1      Adrinne
2       Marcus
3      Patrick
4    Guilherme
5        Denis
6         Enzo
Name: Nome, dtype: object

In [33]:
df[df["Idade"] > 30]

      Nome  Idade Genero
3  Patrick     45      M
5    Denis     40      T

In [34]:
df[df["Genero"] == "T"]

    Nome  Idade Genero
5  Denis     40      T

In [35]:
idade = int(input ("Digite a idade: "))

df[df["Idade"] > idade]

Digite a idade:  20

        Nome  Idade Genero
0     Bianca     22      F
1    Adrinne     29      F
3    Patrick     45      M
4  Guilherme     21      I
5      Denis     40      T

In [37]:
df.to_excel("turmas.xlsx", index = False)

In [1]:
pip install pdfkit

Collecting pdfkit
  Downloading pdfkit-1.0.0-py3-none-any.whl.metadata (9.3 kB)
Downloading pdfkit-1.0.0-py3-none-any.whl (12 kB)
Installing collected packages: pdfkit
Successfully installed pdfkit-1.0.0
Note: you may need to restart the kernel to use updated packages.