In [1]:
# Importa biblioteca principal para análise de dados
import pandas as pd

# Importa biblioteca para exibir tabelas no Jupyter
from IPython.display import display

# Importa bibliotecas para limpar nomes das colunas e textos
import re
import unicodedata

# Faz o Pandas mostrar todas as colunas
pd.set_option("display.max_columns", None)

# Faz o Pandas mostrar até 100 linhas
pd.set_option("display.max_rows", 100)

# Link direto do dataset da NASA
url = "https://data.nasa.gov/docs/legacy/meteorite_landings/Meteorite_Landings.csv"

# Lê o dataset direto do link
df = pd.read_csv(url)

# Função para padronizar os nomes das colunas
def limpar_nome_coluna(nome):
    # Converte o nome da coluna para texto
    nome = str(nome)

    # Remove acentos, caso existam
    nome = unicodedata.normalize("NFKD", nome)
    nome = nome.encode("ascii", "ignore").decode("utf-8")

    # Converte para letras minúsculas
    nome = nome.lower()

    # Remove espaços no começo e no final
    nome = nome.strip()

    # Troca espaços e caracteres especiais por "_"
    nome = re.sub(r"[^a-z0-9]+", "_", nome)

    # Remove "_" do começo e do final
    nome = nome.strip("_")

    # Retorna o nome padronizado
    return nome

# Padroniza os nomes das colunas
df.columns = [limpar_nome_coluna(coluna) for coluna in df.columns]

# Função para extrair o grupo principal da coluna recclass
def extrair_grupo_classe(recclass):
    # Verifica se o valor está vazio
    if pd.isna(recclass):
        return "Sem classe"

    # Converte o valor para texto
    classe = str(recclass).strip()

    # Remove informações depois de vírgula
    # Exemplo: "Iron, IVA" vira "Iron"
    classe = classe.split(",")[0]

    # Remove informações dentro de parênteses
    # Exemplo: "Martian (shergottite)" vira "Martian"
    classe = re.sub(r"\(.*?\)", "", classe)

    # Remove informações depois de hífen
    # Exemplo: "Eucrite-mmict" vira "Eucrite"
    classe = classe.split("-")[0]

    # Remove espaços extras
    classe = classe.strip()

    # Remove números do final da classe
    # Exemplo: "L5" vira "L", "H6" vira "H", "CM2" vira "CM"
    classe = re.sub(r"\d+$", "", classe)

    # Remove espaços extras novamente
    classe = classe.strip()

    # Se depois da limpeza ficar vazio, retorna Sem classe
    if classe == "":
        return "Sem classe"

    # Retorna o grupo principal
    return classe

# Cria a nova coluna grupo_classe
df["grupo_classe"] = df["recclass"].apply(extrair_grupo_classe)

# Mostra algumas linhas para conferir o resultado
display(df[["name", "recclass", "grupo_classe"]].head(30))

# Mostra a quantidade de meteoritos por grupo principal
contagem_grupo_classe = df["grupo_classe"].value_counts().reset_index()

# Renomeia as colunas para ficar mais amigável
contagem_grupo_classe.columns = ["grupo_classe", "quantidade"]

# Mostra a tabela de contagem por grupo principal
display(contagem_grupo_classe.head(30))

                   name       recclass grupo_classe
0                Aachen             L5            L
1                Aarhus             H6            H
2                  Abee            EH4           EH
3              Acapulco    Acapulcoite  Acapulcoite
4               Achiras             L6            L
5              Adhi Kot            EH4           EH
6   Adzhi-Bogdo (stone)          LL3-6           LL
7                  Agen             H5            H
8                Aguada             L6            L
9         Aguila Blanca              L            L
10     Aioun el Atrouss   Diogenite-pm    Diogenite
11                  Aïr             L6            L
12      Aire-sur-la-Lys        Unknown      Unknown
13                Akaba             L6            L
14             Akbarpur             H4            H
15              Akwanga              H            H
16              Akyumak      Iron, IVA         Iron
17              Al Rais         CR2-an           CR
18            Al Zarnkh            LL5           LL
19                Alais            CI1           CI
20             Albareto          L/LL4         L/LL
21              Alberta              L            L
22      Alby sur Chéran  Eucrite-mmict      Eucrite
23            Aldsworth            LL5           LL
24               Aleppo             L6            L
25          Alessandria             H5            H
26        Alexandrovsky             H4            H
27           Alfianello             L6            L
28              Allegan             H5            H
29              Allende            CV3           CV

    grupo_classe  quantidade
0              H       16729
1              L       15090
2             LL        5626
3           Iron        1067
4        Eucrite         681
5             CM         442
6            H4/         434
7            L3.         414
8             CO         336
9       Ureilite         327
10           H3.         314
11     Diogenite         264
12            CV         261
13             E         243
14     Howardite         241
15            CK         208
16           H5/         193
17  Mesosiderite         186
18          LL3.         178
19         Lunar         165
20            EH         160
21            H~         151
22            CR         148
23            L~         139
24       Martian         119
25            EL         114
26           L5/         109
27             R         106
28          L/LL          98
29     Pallasite          93